executar_teste:
  before_script:
    - echo "Preparando ambiente para testes..."
  script:
    - echo "Executando testes..."
  after_script:
    - echo "Limpando ambiente de testes..."    


criar_imagem:
  script:
    - echo "Criando imagem ..."


push_imagem:
  script:
    - echo "Realizando upload das imagens"