import { StyleSheet, Platform } from 'react-native';
import { C } from '../constants';

// ─── Estilos globais (inputs, botões, banners) ────────────────────────────
export const global = StyleSheet.create({
  screen:     { flex: 1, backgroundColor: C.bg },
  safeHeader: {
    paddingTop: Platform.OS === 'android' ? 42 : 56,
    paddingBottom: 14, paddingHorizontal: 18,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: C.card, borderBottomWidth: 1, borderBottomColor: C.border,
  },
  headerTitle:     { fontSize: 20, fontWeight: '800', color: C.text },
  headerSubtitle:  { fontSize: 12, color: C.textMuted, marginTop: 2 },
  headerBadge:     { backgroundColor: C.primaryLight, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4 },
  headerBadgeText: { fontSize: 11, fontWeight: '700', color: C.primary },
  primaryBtn: {
    backgroundColor: C.primary, borderRadius: 14,
    paddingVertical: 15, flexDirection: 'row',
    alignItems: 'center', justifyContent: 'center',
    shadowColor: C.primary, shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28, shadowRadius: 14, elevation: 6,
  },
  primaryBtnDisabled: {
    backgroundColor: '#F3F4F6', shadowOpacity: 0,
    elevation: 0, borderWidth: 1, borderColor: C.border,
  },
  primaryBtnText:         { fontSize: 15, fontWeight: '700', color: '#fff', letterSpacing: 0.2 },
  primaryBtnTextDisabled: { color: C.textMuted },
  fieldLabel: { fontSize: 11, fontWeight: '700', color: C.textMuted, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 7 },
  inputWrap:  { flexDirection: 'row', alignItems: 'center', backgroundColor: C.bg, borderRadius: 12, borderWidth: 1.5, borderColor: C.border, paddingHorizontal: 12, paddingVertical: Platform.OS === 'ios' ? 13 : 9 },
  inputWrapError:    { borderColor: '#E11D48' },
  inputWrapReadOnly: { backgroundColor: '#F3F4F6' },
  inputIcon:  { marginRight: 8 },
  input:      { flex: 1, fontSize: 14, color: C.text, padding: 0 },
  errorRow:   { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  errorText:  { fontSize: 12, color: '#E11D48', fontWeight: '500' },
  warnBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#FEF3C7', borderWidth: 1, borderColor: '#FDE68A', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, marginBottom: 14 },
  warnText:   { fontSize: 13, color: '#92400E', fontWeight: '500', flex: 1 },
  successBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: C.successLight, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 16, borderWidth: 1, borderColor: C.success + '40' },
  successText:   { fontSize: 13, fontWeight: '600', color: C.success },
  divider: { height: 1, backgroundColor: C.border, marginVertical: 16 },
  card:    { backgroundColor: C.card, borderRadius: 20, padding: 20, borderWidth: 1, borderColor: C.border, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 12, elevation: 2 },
  version: { textAlign: 'center', fontSize: 11, color: C.textMuted, marginBottom: 8 },
});

// ─── HistoryScreen ────────────────────────────────────────────────────────
export const hx = StyleSheet.create({
  root:             { flex: 1, backgroundColor: C.bg },
  header:           { paddingTop: Platform.OS === 'android' ? 42 : 56, paddingBottom: 14, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', backgroundColor: C.card, borderBottomWidth: 1, borderBottomColor: C.border, gap: 12 },
  headerTitle:      { fontSize: 17, fontWeight: '800', color: C.text },
  headerSub:        { fontSize: 12, color: C.textMuted, marginTop: 1 },
  pendingBadge:     { backgroundColor: '#FEF3C7', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 4, borderWidth: 1, borderColor: '#FDE68A' },
  pendingBadgeText: { fontSize: 11, fontWeight: '700', color: '#B45309' },
  filterScroll:     { flexGrow: 0, backgroundColor: C.card, borderBottomWidth: 1, borderBottomColor: C.border },
  filterRow:        { paddingHorizontal: 16, paddingVertical: 10, gap: 8, flexDirection: 'row' },
  filterTab:        { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1.5, borderColor: C.border, backgroundColor: C.card },
  filterDot:        { width: 7, height: 7, borderRadius: 4 },
  filterText:       { fontSize: 12, fontWeight: '500', color: C.textSub },
  infoBanner:       { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: C.primaryLight, paddingHorizontal: 16, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: C.primary + '20' },
  infoText:         { fontSize: 12, color: C.primary, flex: 1 },
  listContent:      { paddingHorizontal: 16, paddingTop: 16 },
  emptyWrap:        { alignItems: 'center', paddingTop: 60, paddingHorizontal: 24 },
  emptyIcon:        { width: 80, height: 80, borderRadius: 40, backgroundColor: C.border, alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  emptyTitle:       { fontSize: 18, fontWeight: '800', color: C.text, marginBottom: 8 },
  emptySub:         { fontSize: 14, color: C.textSub, textAlign: 'center', lineHeight: 20, marginBottom: 24 },
  emptyBtn:         { flexDirection: 'row', alignItems: 'center', backgroundColor: C.primary, borderRadius: 14, paddingHorizontal: 20, paddingVertical: 13 },
  emptyBtnText:     { fontSize: 14, fontWeight: '700', color: '#fff' },
  emptyFilter:      { alignItems: 'center', paddingTop: 50, gap: 12 },
  emptyFilterText:  { fontSize: 14, color: C.textSub, textAlign: 'center' },
  fab:              { position: 'absolute', right: 18, bottom: 24, width: 52, height: 52, borderRadius: 26, backgroundColor: C.primary, alignItems: 'center', justifyContent: 'center', shadowColor: C.primary, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.32, shadowRadius: 12, elevation: 8 },
});

// ─── OccurrenceCard ───────────────────────────────────────────────────────
export const oc = StyleSheet.create({
  card:              { backgroundColor: C.card, borderRadius: 18, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: C.border },
  cardTop:           { flexDirection: 'row', alignItems: 'center' },
  typeIconWrap:      { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  typeLabel:         { fontSize: 11, fontWeight: '600', color: C.textMuted, textTransform: 'uppercase', letterSpacing: 0.6 },
  placeName:         { fontSize: 14, fontWeight: '700', color: C.text, marginTop: 1 },
  statusBadge:       { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5 },
  statusText:        { fontSize: 11, fontWeight: '700' },
  divider:           { height: 1, backgroundColor: C.border, marginVertical: 12 },
  metaRow:           { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8, flexWrap: 'wrap' },
  metaItem:          { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metaText:          { fontSize: 11, color: C.textMuted, fontWeight: '500' },
  sevBadge:          { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3 },
  sevDot:            { width: 6, height: 6, borderRadius: 3 },
  sevText:           { fontSize: 11, fontWeight: '700' },
  description:       { fontSize: 13, color: C.textSub, lineHeight: 19, marginBottom: 12 },
  actions:           { flexDirection: 'row', gap: 10 },
  editBtn:           { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 9, borderRadius: 10, borderWidth: 1.5, borderColor: C.primary + '50', backgroundColor: C.primaryLight },
  editText:          { fontSize: 13, fontWeight: '700', color: C.primary },
  deleteBtn:         { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 9, borderRadius: 10, borderWidth: 1.5, borderColor: '#FECDD3', backgroundColor: '#FFF1F2' },
  deleteText:        { fontSize: 13, fontWeight: '700', color: '#E11D48' },
  lockedRow:         { flexDirection: 'row', alignItems: 'center', gap: 5 },
  lockedText:        { fontSize: 11, color: C.textMuted, fontStyle: 'italic' },
  confirmBox:        { backgroundColor: '#FFF1F2', borderRadius: 12, padding: 12, borderWidth: 1.5, borderColor: '#FECDD3' },
  confirmText:       { fontSize: 13, fontWeight: '700', color: '#E11D48', marginBottom: 2 },
  confirmSub:        { fontSize: 11, color: C.textMuted, marginBottom: 10 },
  confirmActions:    { flexDirection: 'row', gap: 8 },
  confirmCancelBtn:  { flex: 1, paddingVertical: 8, borderRadius: 8, borderWidth: 1.5, borderColor: C.border, alignItems: 'center', backgroundColor: C.card },
  confirmCancelText: { fontSize: 13, fontWeight: '600', color: C.textSub },
  confirmDeleteBtn:  { flex: 1, paddingVertical: 8, borderRadius: 8, backgroundColor: '#E11D48', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  confirmDeleteText: { fontSize: 13, fontWeight: '700', color: '#fff' },
});

// ─── EditModal ────────────────────────────────────────────────────────────
export const em = StyleSheet.create({
  overlay:       { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  sheet:         { backgroundColor: C.card, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingTop: 20, paddingBottom: Platform.OS === 'ios' ? 40 : 24 },
  header:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  title:         { fontSize: 17, fontWeight: '800', color: C.text },
  closeBtn:      { width: 32, height: 32, borderRadius: 8, backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center' },
  infoBadge:     { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.bg, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, marginBottom: 18 },
  infoBadgeText: { fontSize: 12, fontWeight: '700' },
  infoBadgeSep:  { color: C.textMuted, marginHorizontal: 2 },
  infoBadgeSub:  { fontSize: 12, color: C.textMuted },
  label:         { fontSize: 11, fontWeight: '700', color: C.textMuted, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8 },
  severityRow:   { flexDirection: 'row', gap: 8, marginBottom: 18 },
  severityPill:  { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 10, borderRadius: 10, borderWidth: 1.5, borderColor: C.border },
  severityDot:   { width: 7, height: 7, borderRadius: 4 },
  severityLabel: { fontSize: 13, color: C.textSub },
  textAreaWrap:  { backgroundColor: C.bg, borderRadius: 12, borderWidth: 1.5, borderColor: C.border, padding: 12, marginBottom: 20 },
  textArea:      { fontSize: 14, color: C.text, minHeight: 90, lineHeight: 21 },
  charCount:     { fontSize: 11, color: C.textMuted, textAlign: 'right', marginTop: 4 },
  actions:       { flexDirection: 'row', gap: 10 },
  cancelBtn:     { flex: 1, paddingVertical: 13, borderRadius: 12, borderWidth: 1.5, borderColor: C.border, alignItems: 'center' },
  cancelText:    { fontSize: 14, fontWeight: '600', color: C.textSub },
  saveBtn:       { flex: 1, paddingVertical: 13, borderRadius: 12, backgroundColor: C.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  saveText:      { fontSize: 14, fontWeight: '700', color: '#fff' },
});

// ─── FormScreen ───────────────────────────────────────────────────────────
export const fs = StyleSheet.create({
  root:         { flex: 1, backgroundColor: C.bg },
  header:       { paddingTop: Platform.OS === 'android' ? 42 : 56, paddingBottom: 14, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: C.card, borderBottomWidth: 1, borderBottomColor: C.border },
  headerTitle:  { fontSize: 17, fontWeight: '700', color: C.text },
  headerBadge:  { backgroundColor: C.primaryLight, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4 },
  headerBadgeText: { fontSize: 11, fontWeight: '700', color: C.primary },
  scroll:       { flex: 1 },
  scrollContent:{ paddingHorizontal: 18, paddingTop: 20 },
  section:      { marginBottom: 22 },
  sectionLabel: { fontSize: 11, fontWeight: '700', color: C.textMuted, letterSpacing: 1.2, textTransform: 'uppercase', marginBottom: 10 },
  req:          { color: '#E11D48', fontWeight: '700' },
  optional:     { color: C.textMuted, fontWeight: '400', letterSpacing: 0, textTransform: 'none', fontSize: 11 },
  helper:       { fontSize: 11, color: C.textMuted, marginTop: 6 },
  inputErr:     { borderColor: '#E11D48', borderWidth: 1.5 },
  cardErr:      { borderColor: '#FECDD3', backgroundColor: '#FFF1F2' },
  errorRow:     { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 6 },
  errorText:    { fontSize: 12, color: '#E11D48', fontWeight: '500', flex: 1 },
  warnBanner:   { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#FEF3C7', borderWidth: 1, borderColor: '#FDE68A', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, marginBottom: 14 },
  warnText:     { fontSize: 13, color: '#92400E', fontWeight: '500', flex: 1 },
  placeCard:    { flexDirection: 'row', alignItems: 'center', backgroundColor: C.card, borderRadius: 16, padding: 14, borderWidth: 1.5, borderColor: C.border },
  placeIconWrap:{ width: 50, height: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginRight: 14 },
  placeInfo:    { flex: 1 },
  placeName:    { fontSize: 15, fontWeight: '700', color: C.text },
  placeAddress: { fontSize: 12, color: C.textSub, marginTop: 2 },
  placeCount:   { fontSize: 11, fontWeight: '600', marginTop: 4 },
  placeChevron: { width: 30, height: 30, borderRadius: 8, backgroundColor: C.primaryLight, alignItems: 'center', justifyContent: 'center' },
  dateBox:      { flexDirection: 'row', alignItems: 'center', backgroundColor: C.card, borderRadius: 14, borderWidth: 1.5, borderColor: C.border, paddingHorizontal: 14, paddingVertical: 13, gap: 10 },
  dateIconWrap: { width: 32, height: 32, borderRadius: 8, backgroundColor: C.primaryLight, alignItems: 'center', justifyContent: 'center' },
  dateText:     { flex: 1, color: C.text, fontSize: 14, fontWeight: '500' },
  autoBadge:    { backgroundColor: '#F3F4F6', borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3 },
  autoBadgeText:{ fontSize: 10, color: C.textMuted, fontWeight: '600' },
  categoriesGrid:    { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  categoryCard:      { width: '47%', backgroundColor: C.card, borderRadius: 14, borderWidth: 1.5, borderColor: C.border, padding: 14, alignItems: 'flex-start', position: 'relative' },
  categoryIconCircle:{ width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  categoryLabel:     { fontSize: 13, fontWeight: '600', color: C.textSub },
  categoryCheck:     { position: 'absolute', top: 10, right: 10, width: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  severityRow:  { flexDirection: 'row', gap: 10 },
  severityPill: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 12, borderRadius: 12, borderWidth: 1.5, borderColor: C.border, backgroundColor: C.card },
  severityDot:  { width: 7, height: 7, borderRadius: 4 },
  severityLabel:{ fontSize: 13, fontWeight: '600', color: C.textSub },
  textAreaWrap: { backgroundColor: C.card, borderRadius: 14, borderWidth: 1.5, borderColor: C.border, padding: 14 },
  textArea:     { color: C.text, fontSize: 14, minHeight: 100, lineHeight: 22 },
  charRow:      { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6 },
  charCount:    { fontSize: 11, color: C.textMuted },
  charHint:     { fontSize: 10, color: '#E11D48' },
  submitBtn:    { backgroundColor: C.primary, borderRadius: 14, paddingVertical: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 4, shadowColor: C.primary, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.28, shadowRadius: 14, elevation: 6 },
  submitBtnDisabled: { backgroundColor: '#F3F4F6', shadowOpacity: 0, elevation: 0, borderWidth: 1, borderColor: C.border },
  submitText:   { fontSize: 16, fontWeight: '700', color: '#fff', letterSpacing: 0.3 },
});

// ─── ConfirmationScreen ───────────────────────────────────────────────────
export const cf = StyleSheet.create({
  root:          { flex: 1, backgroundColor: C.bg },
  topBand:       { position: 'absolute', top: 0, left: 0, right: 0, height: 200, backgroundColor: C.primary, opacity: 0.06, borderBottomLeftRadius: 40, borderBottomRightRadius: 40 },
  scroll:        { flex: 1 },
  content:       { paddingHorizontal: 20, paddingTop: Platform.OS === 'android' ? 64 : 78, alignItems: 'center' },
  iconOuter:     { width: 92, height: 92, borderRadius: 46, backgroundColor: C.success, alignItems: 'center', justifyContent: 'center', marginBottom: 20, shadowColor: C.success, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.35, shadowRadius: 16, elevation: 8, borderWidth: 6, borderColor: C.successLight },
  title:         { fontSize: 26, fontWeight: '800', color: C.text, letterSpacing: -0.3, marginBottom: 8, textAlign: 'center' },
  subtitle:      { fontSize: 14, color: C.textSub, textAlign: 'center', lineHeight: 21, marginBottom: 16, paddingHorizontal: 10 },
  protocolBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.primaryLight, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 7, marginBottom: 28, borderWidth: 1, borderColor: C.primary + '30' },
  protocolText:  { fontSize: 12, fontWeight: '700', color: C.primary },
  card:          { width: '100%', backgroundColor: C.card, borderRadius: 20, padding: 18, marginBottom: 14, borderWidth: 1, borderColor: C.border, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 12, elevation: 3 },
  cardTitle:     { fontSize: 10, fontWeight: '800', color: C.textMuted, letterSpacing: 1.4, textTransform: 'uppercase', marginBottom: 14 },
  row:           { flexDirection: 'row', alignItems: 'flex-start' },
  rowIcon:       { width: 32, height: 32, borderRadius: 8, backgroundColor: C.primaryLight, alignItems: 'center', justifyContent: 'center', marginRight: 12, marginTop: 1 },
  rowLabel:      { fontSize: 10, fontWeight: '700', color: C.textMuted, letterSpacing: 0.8, textTransform: 'uppercase', marginBottom: 3 },
  rowValue:      { fontSize: 14, fontWeight: '700', color: C.text },
  rowSub:        { fontSize: 12, color: C.textSub, marginTop: 2 },
  divider:       { height: 1, backgroundColor: C.border, marginVertical: 12 },
  descText:      { fontSize: 14, color: C.textSub, lineHeight: 20, marginTop: 4 },
  sevTag:        { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5, borderWidth: 1, marginLeft: 8 },
  sevDot:        { width: 7, height: 7, borderRadius: 4 },
  sevTagText:    { fontSize: 12, fontWeight: '700' },
  stepRow:       { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  stepDot:       { width: 28, height: 28, borderRadius: 14, backgroundColor: '#F3F4F6', borderWidth: 1.5, borderColor: C.border, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  stepDotDone:   { backgroundColor: C.success, borderColor: C.success },
  stepLine:      { position: 'absolute', left: 13, top: 28, width: 2, height: 10, backgroundColor: C.border },
  stepLineDone:  { backgroundColor: C.success },
  stepLabel:     { fontSize: 13, fontWeight: '600', color: C.textSub },
  primaryBtn:    { width: '100%', backgroundColor: C.primary, borderRadius: 14, paddingVertical: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginBottom: 12, shadowColor: C.primary, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.28, shadowRadius: 14, elevation: 6 },
  primaryBtnText:{ fontSize: 15, fontWeight: '700', color: '#fff', letterSpacing: 0.2 },
  secondaryBtn:  { width: '100%', backgroundColor: C.card, borderRadius: 14, paddingVertical: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginBottom: 12, borderWidth: 1.5, borderColor: C.primary + '50' },
  secondaryBtnText: { fontSize: 15, fontWeight: '700', color: C.primary },
});
